### ISSUE TITLE
Offtopic: What cursor jump animation plugin are you using 

### ISSUE THREAD

**Issue by 2KAbhishek** [prochri/telescope-all-recent.nvim#10]
Hey great plugin, will definitely try it out soon

I really wanted to know what plugin you are using for the cursor jump animation on the readme screen recording.

**Comment by prochri** [comment]
Hi, hope you like the plugin when trying it!

I use the GUI [neovide](https://github.com/neovide/neovide) for this. If you want to have something like this in the terminal, something like [mini.animate](https://github.com/echasnovski/mini.animate) could work.
