### ISSUE TITLE
Set max frecency for last selected item

### ISSUE THREAD

**Issue by GordianDziwis** [prochri/telescope-all-recent.nvim#12]
I am using this plugin to search all files in the current project with tab. And I would like to change the result so that this behavior is achieved:

1. Buffer with file A is active.
2. Jump with `telescoper-all-recent` to file B.
3. Now when doing a frequency search on the files the result should be:
    1. A
    2. Rest of the files

This would enable me to jump between forward and back between two files. 
The reasoning behind this, that the last opened file should have the highest priority. Can this be done without changing the frequency score in the database?

**Comment by prochri** [comment]
You could use recency sorting to achieve this result, but then, the other files would also have a different sorting.

As an alternative, you could set a much higher recency modifier score for the last 5 minutes or something like this.
Something like this could work (also see the README for that)
```lua
  scoring = {
    recency_modifier = { -- also see telescope-frecency for these settings
      [1] = { age = 5, value = 500 }, -- past 5 minutes
      [2] = { age = 240, value = 100 }, -- past 4 hours
      [3] = { age = 1440, value = 80 }, -- past day
      [4] = { age = 4320, value = 60 }, -- past 3 days
      [5] = { age = 10080, value = 40 }, -- past week
      [6] = { age = 43200, value = 20 }, -- past month
      [6] = { age = 129600, value = 10 } -- past 90 days
    },
    -- how much the score of a recent item will be improved.
    boost_factor = 0.0001
  },
```
However, this could also change the other sorting a little bit.

I personally don't use this plugin for searching files. Instead I use [smart-open.nvim](https://github.com/danielfalk/smart-open.nvim). Maybe this would work better for you!

**Comment by GordianDziwis** [comment]
Thanks a lot, `smart-open` does exactly what I need!
