### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by eddyekofo94** [prochri/telescope-all-recent.nvim#14]
Just installed the plugin yet somehow when I call `vim.keymap.set('n', '<leader>f', function() require'telescope'.builtins.find_files() end)` it seems to give an error `attempt to index field 'builtins' (a nil value)`

**Comment by prochri** [comment]
Telescope does not expose builtins via this import.

This should work:
```
vim.keymap.set('n', '<leader>f', function() require'telescope.builtins'.find_files() end)
```

**Comment by eddyekofo94** [comment]
Still not working unfortunately I cannot get this plugin working at all, I am using NVChad I don't know if there's a correlation there.
