### ISSUE TITLE
Fails to override telescope picker when called from lua

### ISSUE THREAD

**Issue by 1412031** [prochri/telescope-all-recent.nvim#2]
Hey! First of all a bit of appreciation, I've been longing for such functionality ever since I started using telescope and I feel more than happy as the lack of it has long been slowing me down and causing mental unnecessary overhead. Definitely the plugin of the year for me, hehe, thanks a lot!

You could very well be aware of it  and it might not be intended to work this way in any way.

When calling the telescope picker directly from lua code for example
`vim.keymap.set('n', '<leader>f', require'telescope'.builtins.find_files)`

The override process doesn't work at all. And the default picker is used.
I'm mostly opening this issue cause I've spent quite some time trying to figure out why it hasn't installed properly and it turned out to be the way I was invoking telescope, so it might be useful to add a little note in the readme tipping the users about it so they don't end up wasting any time like I did.

you're the man, really thanks for that

**Comment by prochri** [comment]
Hey! Glad you enjoy the plugin!

I have not tested anything, but most likely, you set the keybinding before setting up this plugin.
Thus the keymap refers to the old (not overriden) function and does not work.

So to work around that, you can:

1. Load the plugin first and then set the keymaps
2. Wrap the call in a lua function, like that: `vim.keymap.set('n', '<leader>f', function() require'telescope'.builtins.find_files() end)`. This will resolve the function once the keybinding is pressed.
3. Use any other method of creating the keybinding.

I will add a short section to the README about this.

**Comment by KentVu** [comment]
> Load the plugin first and then set the keymaps

I don't know if adding the keymap to this plugin's lazy spec's `keys` field is sufficient to make it _load first_?

For ex.:
```lua
{
  'prochri/telescope-all-recent.nvim',
  keys = {
   { "<leader>...",  require("telescope")...},
  },
  ...
}
```

**Comment by prochri** [comment]
Tbh, when in doubt, wrap it with a function as in (2.), then it will always use the currently bound function. Then you only have to make sure, that the plugin is loaded correctly. This should also work in lazy's keys section.
