### ISSUE TITLE
Just a message

### ISSUE THREAD

**Issue by otavioschwanck** [prochri/telescope-all-recent.nvim#3]
Man, awesome plugin!  Don't forget to add this to the telescope list on wiki!

**Comment by prochri** [comment]
Glad you enjoy it! Do you know how I would go about getting it added to the wiki?

**Comment by otavioschwanck** [comment]
> Glad you enjoy it! Do you know how I would go about getting it added to the wiki?

i added for you!

https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions#different-plugins-with-telescope-integration

**Comment by prochri** [comment]
Thank you! Closing this then.
