### ISSUE TITLE
some extension is not work

### ISSUE THREAD

**Issue by Mr-LLLLL** [prochri/telescope-all-recent.nvim#5]
require 'telescope-all-recent'.setup {
        default = {
            disable = true, -- disable any unkown pickers (recommended)
            use_cwd = true, -- differentiate scoring for each picker based on cwd
            sorting = 'frecency' -- sorting: options: 'recent' and 'frecency'
        },
        pickers = {
            -- use print(vim.inspect(require'telescope'.extensions)) get extension pickers
            ['project#project'] = {
                disable = false,
                use_cwd = false,
                sorting = 'frecency'
            },
            ['bookmarks#bookmarks'] = {
                disalbe = false,
                use_cwd = false,
                sorting = 'frecency'
            },
        }
    }

i have two extension of telescope project and bookmarks.  project is work, but bookmarks not work, two extension name and method name accord by print(vim.inspect(require'telescope'.extensions))

**Comment by Mr-LLLLL** [comment]
``` lua
 {
  bookmarks = {
    bookmarks = <function 1>
  },
...
  project = {
    project = <function 5>
  },
...
  <metatable> = {
    __index = <function 8>
  }
}
```

print(vim.inspect(require'telescope'.extensions)) result is above

**Comment by prochri** [comment]
I will take a look soon.

You are using this extension: https://github.com/dhruvmanila/telescope-bookmarks.nvim ?

Also can you give some insights, in which order you are loading telescope, the extensions and this plugin?

**Comment by Mr-LLLLL** [comment]
yes, this extension is https://github.com/dhruvmanila/telescope-bookmarks.nvim. i am trying fix this, if it possible.

**Comment by Mr-LLLLL** [comment]
my fault, i found this proble, i config 
``` lua
        ['bookmarks#bookmarks'] = {
            disalbe = false,
            use_cwd = false,
            sorting = 'frecency'
        }, 
```
disalbe is spell error, thank you so much.
