### ISSUE TITLE
Error when executing a custom find_files

### ISSUE THREAD

**Issue by otavioschwanck** [prochri/telescope-all-recent.nvim#7]
E5108: Error executing lua: ...escope-all-recent.nvim/lua/telescope-all-recent/init.lua:24: attempt to index local 'select_opts' (a nil value)
stack traceback:
	...escope-all-recent.nvim/lua/telescope-all-recent/init.lua:24: in function 'establish_vim_ui_select_settings'
	...escope-all-recent.nvim/lua/telescope-all-recent/init.lua:65: in function 'establish_picker_settings'
	...escope-all-recent.nvim/lua/telescope-all-recent/init.lua:98: in function 'on_new_picker'
	...pe-all-recent.nvim/lua/telescope-all-recent/override.lua:123: in function 'new'
	/Users/otavio/.config/nvim/lua/mood-scripts/open-files.lua:11: in function 'call'
	/Users/otavio/.config/nvim/lua/mood-scripts/open-files.lua:67: in function 'open_dotfiles'
	/Users/otavio/.config/nvim/lua/core/mappings.lua:150: in function </Users/otavio/.config/nvim/lua/core/mappings.lua:150>

My find files:

```lua
function M.call(files)
  pickers.new({}, {
    prompt_title = "User Files",
    finder = finders.new_table {
      results = files,
      entry_maker = function(entry)
        return { value = entry.path, display = entry.display or entry.path, ordinal = (entry.order or '') .. (entry.display or '') .. entry.path }
      end
    },
    sorter = conf.generic_sorter({}),
    previewer = conf.file_previewer({}),
    attach_mappings = function(prompt_bufnr, _)
      actions.select_default:replace(function()
        actions.close(prompt_bufnr)
        local selection = action_state.get_selected_entry().value

        vim.cmd("e " .. selection)
      end)
      return true
    end,
  }):find()
end

```

**Comment by prochri** [comment]
The error should be fixed with the pushed commit!

You don't want to have recency sorting for your picker, right?

**Comment by otavioschwanck** [comment]
> The error should be fixed with the pushed commit!
> 
> You don't want to have recency sorting for your picker, right?

Fixed!
