### ISSUE TITLE
show only recent-files when calling find_files

### ISSUE THREAD

**Issue by otavioschwanck** [prochri/telescope-all-recent.nvim#9]
My project has a lot of files (1000+) and i have a delay until load the first screen, and then, i can't select the recent.

Is possible to show only recent files and just search when i type something?

**Comment by prochri** [comment]
So your idea is to only start the search as soon as you type any letter?

Sounds like an interesting idea, but here are some problems to this:
- It is hard to check, if the cached files (or in general menu options) still exist. What would happen, when you select a non existing option?
- In the current design, only the scoring is adjusted based on recency. Creating new items is not supported (currently), but would be needed for this to work.
- It would just defer the loading time until the first letter is typed in, if implemented in an naive way.
- I think that this is mostly related to this single problem: finding files. Or did you notice any usability concern in other pickers?
As this plugin aims to be as general as possible, it might be better to address this using a dedicated find files plugin.

Regarding find_files in your project, ignore irrelevant files, e.g. by using a `.rgignore` file.

Let me know your thoughts on this!

**Comment by otavioschwanck** [comment]
> So your idea is to only start the search as soon as you type any letter?

Yes

> It is hard to check, if the cached files (or in general menu options) still exist. What would happen, when you select a non existing option?

Good point, i think for each item, verify if still exists, if not, don't show.  The default history size is 10, i think is viable, right?

> In the current design, only the scoring is adjusted based on recency. Creating new items is not supported (currently), but would be needed for this to work.

i didn't understand that

> It would just defer the loading time until the first letter is typed in, if implemented in an naive way.

ok

> I think that this is mostly related to this single problem: finding files. Or did you notice any usability concern in other pickers?

For me, just on find_files, it has so much files in my project and if take a few milliseconds to stop loading and i use all the time.

> Regarding find_files in your project, ignore irrelevant files, e.g. by using a .rgignore file.

i will give a try.

About the issue, i thing the power of find-files would be increased a lot with this.  It could even be used to switch between recent files

**Comment by prochri** [comment]
>>  It is hard to check, if the cached files (or in general menu options) still exist. What would happen, when you select a non existing option?

> Good point, i think for each item, verify if still exists, if not, don't show. The default history size is 10, i think is viable, right?

For files, this would be no problem. But there is no generic way to do this without invoking the actual finder.

>>  In the current design, only the scoring is adjusted based on recency. Creating new items is not supported (currently), but would be needed for this to work.

> i didn't understand that

The current architecture is like this: Finder creates items (in this case files) with some scoring, this plugin looks up each item and adjusts the scoring to prefer more recent items. So, without invoking the finder, this plugin currently can't do anything.

> About the issue, i thing the power of find-files would be increased a lot with this. It could even be used to switch between recent files

I understand, that this functionality would be nice. But a dedicated plugin for finding files would be the more appropriate solution in my opinion. (I also use a dedicated plugin for this sometimes, like this: https://github.com/danielfalk/smart-open.nvim but it is also not ideal for large projects)

**Comment by otavioschwanck** [comment]
> > > It is hard to check, if the cached files (or in general menu options) still exist. What would happen, when you select a non existing option?
> 
> > Good point, i think for each item, verify if still exists, if not, don't show. The default history size is 10, i think is viable, right?
> 
> For files, this would be no problem. But there is no generic way to do this without invoking the actual finder.
> 
> > > In the current design, only the scoring is adjusted based on recency. Creating new items is not supported (currently), but would be needed for this to work.
> 
> > i didn't understand that
> 
> The current architecture is like this: Finder creates items (in this case files) with some scoring, this plugin looks up each item and adjusts the scoring to prefer more recent items. So, without invoking the finder, this plugin currently can't do anything.
> 
> > About the issue, i thing the power of find-files would be increased a lot with this. It could even be used to switch between recent files
> 
> I understand, that this functionality would be nice. But a dedicated plugin for finding files would be the more appropriate solution in my opinion. (I also use a dedicated plugin for this sometimes, like this: https://github.com/danielfalk/smart-open.nvim but it is also not ideal for large projects)

this smart open is exactly what i was looking for, thank you!

**Comment by otavioschwanck** [comment]
tried for a couple of hours smart open and the search is not very efficient for me.  Still searching for a solution to not show the results until start to search

**Comment by prochri** [comment]
Sorry that smart open is not the solution for you.
However, I currently see no generic and convenient way to integrate such functionality into this plugin.

If you have a concrete idea to build this, feel free to share it here or create a pull request.
I will close this issue here for now.
